### ISSUE TITLE
any notes on building and running on Linux?

### ISSUE THREAD

**Issue by AleXoundOS** [heinermann/ChkForge#44]
Are there any source code parts or dependencies which are expected to have issues on Linux?

**Comment by heinermann** [comment]
Yeah stuff imported from ChkDraft won't run on Linux.

**Comment by AleXoundOS** [comment]
Is the C++ code in ChkDraft that much incompatible with GCC?

**Comment by heinermann** [comment]
I'm not sure. If I ever revisit the project I can rebase and see if I can decouple the windows code

**Comment by AleXoundOS** [comment]
Are there any other potential blockers besides ChkDraft?

**Comment by heinermann** [comment]
There shouldn't be. OpenBW is cross platform. Qt is cross platform. This project isn't using Windows API at all.

**Comment by AleXoundOS** [comment]
> Yeah stuff imported from ChkDraft won't compile or run on Linux.

First step would be building ChkDraft with [Winelib/Winemaker](https://wiki.winehq.org/Winelib_User's_Guide#Support_for_Visual_C.2B.2B_projects) (https://github.com/TheNitesWhoSay/Chkdraft/issues/99), producing a binary which works at least via Wine layer _(I remember doing a similar trick with BWAPI back in 2012, but there was no Windows GUI involved)_.
Rewrite in Qt is planned (https://github.com/TheNitesWhoSay/Chkdraft/issues/105), but hasn't begun.

For now, I will close the issue, since currently there is no point in building every part except ChkDraft. Once ChkDraft is able to build and run on Linux and if other ChkForge build issues arise, I will reopen this issue.

**Comment by TheNitesWhoSay** [comment]
I'm pretty sure it didn't work quite like this in ChkForge when we tried, but my intention was for MappingCoreLib from Chkdraft to not be windows dependent and be usable independent from ChkdraftLib and WindowsLib (which are windows dependent), since I don't actively develop on Linux there's likely many issues or unimplemented pieces that would yet need attention and hein may or may not be still borrowing some pieces from ChkdraftLib.

My attention is elsewhere for the forseeable future but just wanted to drop the notes if you're determined to get an editor building on linux build soon.
